### ISSUE TITLE
Bug: 로그아웃한 후 같은 번호로 또 가입이 되는 이슈

### ISSUE THREAD

**Issue by JYPSloth** [wafflestudio19-5/team3-android#26]
로그아웃한 후 다시 로그인해보려고 했는데 제가 비밀번호를 까먹은 것인지 이메일 혹은 비밀번호가 계속 잘못되었다고 나와서(이메일 혹은 사용자이름을 입력하라고 되어 있었는데, 사용자이름을 치니 로그인이 되지 않았습니다) 재가입을 진행하였습니다. 그런데 같은 전화번호로 또 가입이 되어서, 전화번호 정보가 유일하지 않아도 가입이 가능한 것인지 궁금합니다.

**Comment by kwish2** [comment]
네 맞습니다 1) 전화번호는 따로 중복을 확인하지 않고 여러개의 계정을 만들 수 있도록 했습니다. 다만 사용자 이름이나 이메일 주소는 중복을 허용하지 않습니다. 2 ) 원래 로그인 할 때는 이메일을 입력하는 데 ui 상 이메일 주소 또는 사용자 이름이라고 잘못 표기되는 오류가 있었습니다. 

제보 감사합니다

**Comment by kwish2** [comment]
로그인 ui 수정해서 배포했습니다!
