### ISSUE TITLE
Bug: 자기 자신 팔로우

### ISSUE THREAD

**Issue by jsm0424** [wafflestudio19-5/team3-android#27]
자기 자신을 팔로우하면 앱이 종료되는 버그가 있는 것 같습니다!

**Comment by esc5221** [comment]
https://user-images.githubusercontent.com/37990664/148635671-83631a46-5eca-4095-8860-143d31a35e8f.mp4

저도 같은 오류가 있습니다

**Comment by JYPSloth** [comment]
팔로우 관련해서, 팔로잉 목록에 들어가 보면 이미 팔로우한 사람인데 팔로우 버튼이 활성화되어 있고 버튼을 누르면 튕기는 문제도 있는 것 같습니다.

**Comment by esc5221** [comment]
> 팔로우 관련해서, 팔로잉 목록에 들어가 보면 이미 팔로우한 사람인데 팔로우 버튼이 활성화되어 있고 버튼을 누르면 튕기는 문제도 있는 것 같습니다.

https://github.com/wafflestudio19-5/team3-android/issues/31

**Comment by kwish2** [comment]
네 맞습니다. 아직 팔로우 기능이 많이 불안정합니다. 최대한 빠른 시일 내 수정하도록 하겠습니다.

다들 감사드립니다

**Comment by kwish2** [comment]
관련 문제 해결해서 배포했습니다!
