### ISSUE TITLE
Bug: 게시글 작성 시 사진 선택에서 뒤로가기를 누르면 튕기는 현상

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio19-5/team3-android#28]
사진을 선택하지 않고 뒤로가기를 누르면 
![image](https://user-images.githubusercontent.com/88367636/148635685-8ef668ac-d805-4653-82ac-36c80f0cae1a.png)
여기로 이동하고, 게시 버튼을 누르면 튕깁니다.

**Comment by kwish2** [comment]
위 문제 해결했습니다. 감사합니다

**Comment by kwish2** [comment]
해당 문제 해결해서 배포했습니다. 제보 감사합니다!
