### ISSUE TITLE
Fix: 댓글 입력 후, 댓글 내용이 남아있습니다.

### ISSUE THREAD

**Issue by esc5221** [wafflestudio19-5/team3-android#29]
댓글 작성이 끝나면 입력 창의 내용이 없어져야 좋을것 같습니다.

https://user-images.githubusercontent.com/37990664/148635755-5a765083-8930-46d3-8ee9-e4695d799a66.mp4

**Comment by JYPSloth** [comment]
추가로 댓글 입력하는 레이아웃에는 유저프로필이미지가 띄워지지 않는데, 띄워지도록 하면 좋을 것 같습니다!

**Comment by kwish2** [comment]
의견 감사드립니다

**Comment by kwish2** [comment]
수정해서 배포했습니다. 제보 감사합니다!
