### ISSUE TITLE
Bug : 댓글 작성 시 EditText 초기화 

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio19-5/team3-android#30]
![image](https://user-images.githubusercontent.com/88367636/148635747-3bf170b9-9838-4fbf-b621-76f5235ca1a2.png)
게시 버튼을 눌러도 EditText 의 내용이 남아있습니다.

**Comment by esc5221** [comment]
https://github.com/wafflestudio19-5/team3-android/issues/29
같은내용이네요

**Comment by JuTaK97** [comment]
> #29 같은내용이네요

헉 그러네요

**Comment by kwish2** [comment]
수정해서 배포했습니다. 제보 감사합니다!
