### ISSUE TITLE
Bug: 이미 팔로우한 계정의 팔로우 버튼이 활성화 상태 / 버튼 누를시 튕김

### ISSUE THREAD

**Issue by esc5221** [wafflestudio19-5/team3-android#31]
이미 팔로우한 계정의 팔로우 버튼이 파란색으로 활성화 되어있고, 이상태에서 버튼을 누르면 튕기게 됩니다.

https://user-images.githubusercontent.com/37990664/148635866-7c6f1cff-6e30-4198-9142-d25fee7d5fe7.mp4

**Comment by kwish2** [comment]
해당 문제 해결해서 배포했습니다. 제보 감사합니다!
