### ISSUE TITLE
Bug: 구글 로그인 불가능

### ISSUE THREAD

**Issue by hansmaan** [wafflestudio19-5/team3-android#32]
구글 로그인 시도시 400 Bad request가 나옵니다

**Comment by B0neh3ad** [comment]
facebook 로그인이랑 마찬가지로 google 로그인도 아직 구현이 마무리 되지 않아 생긴 오류 같습니다.. 제보 감사드립니다. 빠른 시일 내 수정하겠습니다.

**Comment by B0neh3ad** [comment]
해결했습니다. 다시 한번 제보 감사드립니다.
