### ISSUE TITLE
유저 프로필에서 X를 눌러 로그아웃을 하고, 뒤로가기를 누르면 유저 프로필 창으로 돌아가는 오류

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio19-5/team3-android#33]
![KakaoTalk_20220108_163706856](https://user-images.githubusercontent.com/88367636/148636149-f4fa9e02-a363-41fd-80ef-9e56284040e4.gif)
저렇게 돌아가면 곧 튕깁니다

**Comment by kwish2** [comment]
해당 부분 수정했습니다. 감사합니다

**Comment by kwish2** [comment]
배포 완료했습니다. 감사합니다
