### ISSUE TITLE
Bug: 이미지를 선택하지 않으면 튕김

### ISSUE THREAD

**Issue by esc5221** [wafflestudio19-5/team3-android#34]
* 이미지를 선택하지 않고 이미지를 다시 누르면 튕김
*  이미지를 선택하지 않고 이미지 게시 버튼을 누르면 튕김

https://user-images.githubusercontent.com/37990664/148636081-4251ceee-7f99-4fe3-add7-8ef2bcc98279.mp4

**Comment by kwish2** [comment]
해당 문제 해결해서 배포했습니다. 제보 감사합니다!
