### ISSUE TITLE
Bug: 팔로우 했음에도 프로필 들어가면 팔로우 버튼이 나옴

### ISSUE THREAD

**Issue by hansmaan** [wafflestudio19-5/team3-android#35]
제목 그대로 입니다
![Screenshot_20220108-163945_Wafflestagram.jpg](https://user-images.githubusercontent.com/88359757/148636203-cda56425-1921-48c9-b34a-461efc2b0adf.jpg)

팔로우한 계정인데 이렇게 나오네요

**Comment by kwish2** [comment]
해당 문제 해결해서 배포했습니다. 제보 감사합니다
