### ISSUE TITLE
Bug : 좋아요 표시

### ISSUE THREAD

**Issue by hansmaan** [wafflestudio19-5/team3-android#36]
분명 좋아요를 눌렀고, 반영이 되어있음에도 글쓴이 프로필 조회했다가 해당 게시물 들어가니 빨간 하트표시가 보이지 않습니다.

![Screenshot_20220108-164218_Wafflestagram.jpg](https://user-images.githubusercontent.com/88359757/148636283-ac45b0a0-37dd-46b3-afb0-0b9a23472902.jpg)

**Comment by kwish2** [comment]
확인했습니다 제보 감사드립니다!

**Comment by kwish2** [comment]
해당 부분 수정해서 배포했습니다. 감사합니다
