### ISSUE TITLE
Bug: 피드프래그먼트 새로고침을 하면 모든 피드의 업로드 시간이 갱신한 시각으로 바뀌어서 보입니다.

### ISSUE THREAD

**Issue by JYPSloth** [wafflestudio19-5/team3-android#37]
또한 있는 피드를 다 본 이후에는 스크롤이 끝나는 것이 아니라 최신 피드부터 다시 보이기 시작합니다.

https://user-images.githubusercontent.com/79616126/148636735-809f919e-b7ea-42ad-b402-68bb1b3a7f8d.mp4

**Comment by kwish2** [comment]
해당 문제 해결했습니다. 감사합니다

**Comment by kwish2** [comment]
해당 부분 수정해서 배포했습니다. 감사합니다
