### ISSUE TITLE
Bug: 로그인 하지 않은채로 뒤로가기를 누르면 진행 가능

### ISSUE THREAD

**Issue by tjdqhrdkdl** [wafflestudio19-5/team3-android#38]
첫 로그인 화면에서 뒤로가기를 누르면 로그인된 화면을 볼 수 있습니다.
피드 탭과 검색 탭 모두 들어갈 수 있지만, 피드에는 아무 것도 나타나지는 않습니다.
그리고 프로필 탭을 클릭하면, '유저정보를 확인할 수 없습니다' 메시지와 함께 튕깁니다,

**Comment by kwish2** [comment]
수정하겠습니다. 제보 감사드립니다

**Comment by kwish2** [comment]
해당 부분 수정해서 배포했습니다. 감사합니다
