### ISSUE TITLE
Bug: 무한 페이지네이션

### ISSUE THREAD

**Issue by esc5221** [wafflestudio19-5/team3-android#39]
스크롤을 아래로 하게되면 같은 내용의 게시물이 계속 나타납니다.

https://user-images.githubusercontent.com/37990664/148636809-3d0fe5b0-7571-42a3-b116-8b724bbe5d50.mp4

**Comment by kwish2** [comment]
관련 문제 해결하고 있습니다. 감사합니다

**Comment by kwish2** [comment]
무한 스크롤 이슈 해결하여 배포하였습니다. 감사합니다
