### ISSUE TITLE
Bug: 다크 모드 미지원

### ISSUE THREAD

**Issue by VioletXF** [wafflestudio19-5/team3-android#40]
![image](https://user-images.githubusercontent.com/27609690/148637131-47f31d80-eded-4603-8fbf-af036504ada4.png)

시스템 테마가 다크 모드일 때, 화면이 거의 보이지 않는 문제가 발생합니다. 다크 모드에 대응하도록 styles.xml에서 색상을 적절히 지정하거나, 아래의 코드를 통해 강제로 다크 모드를 사용하지 않도록 설정해야 합니다.
`AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);`

[자세한 내용](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme?hl=ko)

**Comment by kwish2** [comment]
소중한 의견 감사합니다 👍

**Comment by kwish2** [comment]
이제 다크모드를 지원합니다! 다크모드 지원을 적용한 버젼을 배포했습니다. 감사합니다
