### ISSUE TITLE
Bug: 페이스북 로그인 불가

### ISSUE THREAD

**Issue by MinnieMinwoo** [wafflestudio19-5/team3-android#42]
페이스북 연동 시도시 앱 설정 안 됨: 이 앱은 아직 개발 모드 상태이며 회원님께는 액세스 권한이 없습니다. 등록된 테스트 사용자로 전환하거나 앱 관리자에게 권한을 오청하세요
라는 메시지가 뜨면서 로그인이 불가능합니다...!

**Comment by B0neh3ad** [comment]
아직 소셜 로그인 구현이 마무리되지 않아 생긴 오류 같네요. 제보 감사드립니다. 빠른 시일 내 수정하겠습니다.

**Comment by B0neh3ad** [comment]
해결했습니다. 다시 한번 제보 감사드립니다.
